filter:
    excluded_paths: [ tests/* ]

checks:
    php: true

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                override:
                    -
                        command: vendor/bin/phpunit
                        coverage:
                            file: .coverage/coverage.xml
                            format: clover
